array_width = 100
attr_fn_like_width = 100
chain_width = 100
edition = "2018"
fn_args_layout = "Tall" # default
fn_cell_width = 100
force_explicit_abi = true # default
hard_tabs = false # default
max_width = 100
merge_derives = true # default
newline_style = "Auto" # default
remove_nested_parens = true # default
reorder_imports = false
reorder_modules = true # default
single_line_if_else_max_width = 100
struct_lit_width = 100
struct_variant_width = 100
tab_spaces = 4 # default
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
width_heuristics = "Max"

# unstable
#binop_separator = "Front" # default
#blank_lines_lower_bound = 0 # default
#blank_lines_upper_bound = 1 # default
#brace_style = "PreferSameLine"
#color = "Auto" # default
#combine_control_expr = true
#comment_width = 100
#condense_wildcard_suffixes = true
#control_brace_style = "AlwaysSameLine" # default
#disable_all_formatting = false # default
#emit_mode = "Files"
#empty_item_single_line = true # default
#enum_discrim_align_threshold = 20
#error_on_line_overflow = false # default
#error_on_unformatted = false # default
#fn_args_density = "Tall" # default
#fn_single_line = true
#force_explicit_abi = true # default
#force_multiline_blocks = false # default
#format_doc_comments = true
#format_macro_bodies = true # default
#format_macro_matchers = true
#format_strings = true
#hide_parse_errors = false
#ignore = []
#imports_indent = "Block" # default
#imports_layout = "HorizontalVertical"
#indent_style = "Block"
#inline_attribute_width = 0 # default
#license_template_path = ""
#make_backup = false
#match_arm_blocks = false
#match_block_trailing_comma = true
#merge_imports = true
#normalize_comments = true
#normalize_doc_attributes = true
#overflow_delimited_expr = true
#reorder_impl_items = true
#report_fixme = "Never" # default
#report_todo = "Never" # default
#required_version = "1.1.0"
#skip_children = false # default
#space_after_colon = true # default
#space_before_colon = false # default
#spaces_around_ranges = false # default
#struct_field_align_threshold = 20
#struct_lit_single_line = true # default
#trailing_comma = "Vertical" # default
#trailing_semicolon = true # default
#type_punctuation_density = "Wide" # default
#unstable_features = true
#version = "Two"
#where_single_line = true
#wrap_comments = true
